booktime/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("api-auth/", include("rest_framework.urls")),
    path("", include("main.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

main/urls.py
#Django
from rest_framework import routers
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView

#Project
from . import views
from main import endpoints
from main import forms
from main import views
from main import models

router = routers.DefaultRouter()
router.register(r'orderlines', endpoints.PaidOrderLineViewSet)
router.register(r'orders', endpoints.PaidOrderViewSet)



urlpatterns = [
        path(
            "order/done/",
            TemplateView.as_view(template_name="order_done.html"),
            name="checkout_done",
        ),
        path(
            "order/address_select/",
            views.AddressSelectionView.as_view(),
            name="address_select",
        ),
        path("basket/", views.manage_basket, name="basket"),
        path(
            "add_to_basket/",
            views.add_to_basket,
            name="add_to_basket",
        ),
        path(
            "address/",
            views.AddressListView.as_view(),
            name="address_list",
        ),
        path(
            "address/create/",
            views.AddressCreateView.as_view(),
            name="address_create",
        ),
        path(
            "address/<int:pk>/",
            views.AddressUpdateView.as_view(),
            name="address_update",
        ),
        path(
            "address/<int:pk>/delete/",
            views.AddressDeleteView.as_view(),
            name="address_delete",
        ),
        path(
            "product/<slug:slug>/",
            DetailView.as_view(model=models.Product),
            name="product",
        ),
        path(
            "products/<slug:tag>/",
            views.ProductListView.as_view(),
            name="products",
        ),
        path("signup/", views.SignupView.as_view(), name="signup"),
        path(
            "login/",
            auth_views.LoginView.as_view(
                template_name="login.html",
                form_class=forms.AuthenticationForm,
            ),
            name="login",
        ),
        path(
            "logout/", auth_views.LogoutView.as_view(), name="logout"
        ),
        path(
            "contact-us/",
            views.ContactUsView.as_view(),
            name="contact_us",
        ),
        path(
            "about-us/",
            TemplateView.as_view(template_name="about_us.html"),
            name="about_us",
        ),
        path(
            "",
            TemplateView.as_view(template_name="home.html"),
            name="home",
        ),
        path("api/", include(router.urls)),
    
]

main/models.py
from django.db import models
import logging
from django.contrib.admin import ModelAdmin
from django.contrib.auth.admin import (
UserAdmin as DjangoUserAdmin
)
from django.utils.html import format_html
from django.db.models.functions import TruncDay
from django.db.models import Avg, Count, Min, Sum
from django.urls import path
from django.template.response import TemplateResponse
from django.core.validators import MinValueValidator
from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager,
)

logger = logging.getLogger(__name__)

#python manage.py migrate --run-syncdb

class ProductAdmin(admin.ModelAdmin):
    list_display = ("name", "slug", "in_stock", "price")
    list_filter = ("active", "in_stock", "date_updated")
    list_editable = ("in_stock",)
    search_fields = ("name",)
    prepopulated_fields = {"slug": ("name",)}
    autocomplete_fields = ("tags",)

    def get_readonly_fields(self, request, obj=None):
        if request.user.is_superuser:
            return self.readonly_fields
        return list(self.readonly_fields) + ["slug", "name"]

    def get_prepopulated_fields(self, request, obj=None):
        if request.user.is_superuser:
            return self.prepopulated_fields
        else:
            return {}
        
        
class DispatchersProductAdmin(ProductAdmin):
    readonly_fields = ("description", "price", "tags", "active")
    prepopulated_fields = {}
    autocomplete_fields = ()
    
class ProductTagAdmin(admin.ModelAdmin):
    list_display = ("name", "slug")
    list_filter = ("active",)
    search_fields = ("name",)
    prepopulated_fields = {"slug": ("name",)}
    
    def get_readonly_fields(self, request, obj=None):
        if request.user.is_superuser:
            return self.readonly_fields
        return list(self.readonly_fields) + ["slug", "name"]
    
    def get_prepopulated_fields(self, request, obj=None):
        if request.user.is_superuser:
            return self.prepopulated_fields
        else:
            return {}
        
class ProductImageAdmin(admin.ModelAdmin):
    list_display = ("thumbnail_tag", "product_name")
    readonly_fields = ("thumbnail",)
    search_fields = ("product__name",)
    
    def thumbnail_tag(self, obj):
        if obj.thumbnail:
            return format_html(
                '<img src="%s"' % obj.thumbnail.url
            )
        return "-"
    
    
class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class ProductTag(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Product(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    tags = models.ManyToManyField(ProductTag, blank=True)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)

    objects = ActiveManager()

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(
        upload_to="product-thumbnails", null=True
    )


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(
                "Superuser must have is_staff=True."
            )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                "Superuser must have is_superuser=True."
            )

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    username = None
    email = models.EmailField("email address", unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def is_employee(self):
        return self.is_active and (
            self.is_superuser
            or self.is_staff
            and self.groups.filter(name="Employees").exists()
        )

    @property
    def is_dispatcher(self):
        return self.is_active and (
            self.is_superuser
            or self.is_staff
            and self.groups.filter(name="Dispatchers").exists()
        )

class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code = models.CharField(
        "ZIP / Postal code", max_length=12
    )
    city = models.CharField(max_length=60)
    country = models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )
        
class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, "Open"), (SUBMITTED, "Submitted"))
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True
    )
    status = models.IntegerField(choices=STATUSES, default=OPEN)
    
    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())
    
    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException(
                "Cannot create order whitout user"
            )
        
        logger.info(
            "Creating order for basket_id=%d"
            ", shipping_address_id=%d, billing_address_id=%d",
            self.id,
            shipping_address.id,
            billing_address.id,
        )
        order_data = {
            "user":self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }
        order = Order.objects.create(**order_data)
        c=0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order": order,
                    "product": line.product,
                }
                order_line = OrderLine.objects.create(
                    **order_line_data
                )
                c += 1
        logger.info(
            "Created order with id=%d and lines_count=%d",
            order.id,
            c,
        )
        self.status = Basket.SUBMITTED
        self.save()
        return order      
        
    
    
class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1)]
    )

class Order(models.Model):
    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = ((NEW, "New"), (PAID, "Paid"), (DONE, "Done"))
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)
    
    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(
        max_length=60, blank=True
    )
    billing_zip_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)
    
    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(
        max_length=60, blank=True
    )
    
    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)
    

main/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.contrib.auth import authenticate
from django.core.mail import send_mail
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm
)
from django.contrib.auth.forms import UsernameField
from . import models
from . import widgets

import logging
logger = logging.getLogger(__name__)

class ContactForm(forms.Form):
    name = forms.CharField(label="Your name", max_length=100)
    message = forms.CharField(
        max_length=600, widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "site@booktime.domain",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
        )
        message = "Welcome {}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to BookTime",
            message,
            "site@booktime.domain",
            [self.cleaned_data["email"]],
            fail_silently=True,
        )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        strip=False, widget=forms.PasswordInput
    )

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user = authenticate(
                self.request, email=email, password=password
            )
            if self.user is None:
                raise forms.ValidationError(
                    "Invalid email/password combination."
                )
            logger.info(
                "Authentication successful for email=%s", email
            )

        return self.cleaned_data

    def get_user(self):
        return self.user


BasketLineFormSet = inlineformset_factory(
    models.Basket,
    models.BasketLine,
    fields=("quantity",),
    extra=0,
    widgets={"quantity": widgets.PlusMinusNumberInput()},
)


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(queryset=None)
    shipping_address = forms.ModelChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields["billing_address"].queryset = queryset
        self.fields["shipping_address"].queryset = queryset

main/templates/main/address_form.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn- primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/address_list.html
{% extends "base.html" %}
{% block content %}
<h1>List of your addresses:</h1>
{% for address in object_list %}
<p>
    {{ address.name }}<br>
    {{ address.address1 }}<br>
    {{ address.address2 }}<br>
    {{ address.city }}<br>
    {{ address.get_country_display }}<br>
</p>
<p>
    <a href="{% url"address_update" address.id %}">Update
        address</a>
</p>
<p>
    <a href="{% url"address_delete" address.id %}">Delete
        address</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<p>
    <a href="{% url"address_create" %}">Add new address</a>
</p>
{% endblock content %}

main/templates/main/address_update.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn- primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Delete address</h2>
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete it?</p>
    <button type="submit" class="btn btn- primary">Submit
    </button>
</form>
{% endblock content %}

main/templates/main/order_filter.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}

{% block content %}
    <h2>Order dashboard</h2>
    <form method="get">
        {{ filter.form.as_p }}
        <input type="submit"/>
    </form>
    <p>
        {% render_table filter.qs %}
    </p>
{% endblock content %}

main/templates/main/product_detail.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}
  <h1>products</h1>
  <table class="table">
    <tr>
      <th>Name</th>
      <td>{{ object.name }}</td>
    </tr>
    <tr>
      <th>Cover images</th>
      <td>
        <div id="imagebox">
          Loading...
        </div>
      </td>
    </tr>
    <tr>
      <th>Price</th>
      <td>{{ object.price }}</td>
    </tr>
    <tr>
      <th>Description</th>
      <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
      <th>Tags</th>
      <td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
    </tr>
    <tr>
      <th>In stock</th>
      <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
      <th>Updated</th>
      <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
  </table>
  <a href="{% url "add_to_basket" %}?product_id={{ object.id }}">Add to basket</a>
{% endblock content %}

{% block js %}
  {% render_bundle 'imageswitcher' 'js' %}
  <script>
    document.addEventListener("DOMContentLoaded", function (event) {
      var images = [
        {% for image in object.productimage_set.all %}
          {
            "image": "{{ image.image.url|safe }}",
            "thumbnail": "{{ image.thumbnail.url|safe }}"
          },
        {% endfor %}
      ]
      ReactDOM.render(React.createElement(ImageBox, {
        images: images,
        imageStart: images[0]
      }), document.getElementById('imagebox'));
    });
  </script>
{% endblock %}

main/templates/main/product_list.html
{% extends "base.html" %}

{% block content %}
  <h1>products</h1>
  {% for product in page_obj %}
    <p>{{ product.name }}</p>
    <p>
      <a href="{% url "product" product.slug %}">See it here</a>
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{page_obj.previous_page_number}}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Previous</a>
        </li>
      {% endif %}
      {% for pagenum in page_obj.paginator.page_range %}
        <li
          class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
          <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endblock content %}